name: Pitch
description: Explain a concept in a complete, consistent format so you and others can evaluate it
labels: [pitch]
body: 
  - type: markdown
    attributes:
      value: "This prompt is for writing a pitch as described in [Shape Up](https://basecamp.com/shapeup/1.5-chapter-06), the e-book outlining how Basecamp works."
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: "The raw idea, a use case, or something we’ve seen that motivates us to work on this"
  - type: textarea
    id: appetite
    attributes:
      label: Appetite
      description: "How much time we want to spend and how that constrains the solution"
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: "The core elements we came up with, presented in a form that’s easy for people to immediately understand"
  - type: textarea
    id: rabbit-holes
    attributes:
      label: Rabbit holes
      description: "Details about the solution worth calling out to avoid problems"
  - type: textarea
    id: no-gos
    attributes:
      label: No-gos
      description: "Anything specifically excluded from the concept: functionality or use cases we intentionally aren’t covering to fit the appetite or make the problem tractable"